// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbwawgsradaesgwselra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNid2F3Z3NyYWRhZXNnd3NlbHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjY1MDYsImV4cCI6MjA2MDc0MjUwNn0.2ODbqV48qGuuLzZ4aQaiIaQNbFvstSX_-CataPbAeQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);